Adjustments to the examples "Use getters and setters" ("Objects and Data Structures")
thangchung/clean-code-dotnet pull request #117
Opened 2022-07-13 16:21 UTC by jarosal

- added missing type to constructor
- fixed mistake of signature name
- changed double to recommended "decimal" type for money operations
- corrected exception message type from char to string

2022-07-14 05:12 UTC, dmitryvhf approved these changes

2022-07-14 05:13 UTC, dmitryvhf requested changes

2022-07-14 05:13 UTC, dmitryvhf commented on README.md
> +    public BankAccount(decimal balance = 1000)
Must be "double", not decimal

2022-07-14 16:59 UTC, dmitryvhf commented on README.md
> +    public BankAccount(decimal balance = 1000)
> Decimal is the recommended type for currency (unless I'm missing something) so maybe we should use it instead of double in those examples?

This is code for sample. Don't create complications. ;)
But if change, then change everywhere - Bad, Good examples.

2022-07-15 15:03 UTC, dmitryvhf approved these changes

2022-07-15 15:15 UTC, dmitryvhf commented
I propose to change the name of PR and description.

Title: Adjustments to the examples "Use getters and setters" ("Objects and Data Structures")
Description: - fixed mistake of signature name
- changed double to recommended "decimal" type for money operations
- corrected lead/trail symbols to C# codestyle

2022-07-15 15:52 UTC, jarosal commented
@dmitryvhf who has the rights to merge?

2022-07-15 18:23 UTC, dmitryvhf commented
> @dmitryvhf who has the rights to merge?

Check another merge's. I think only Author. Forget and waiting. Not soon, not never. :)

2022-07-16 13:05 UTC, jarosal commented
@thangchung mind taking a look?

2023-04-13 16:53 UTC, closed without merging